#!/usr/bin/env bash
#
# Tests for the rendered-env-file helpers. INF-051.
#
#   ./scripts/lib/env-file.test.sh
#
# The bug these guard against produced no error, no missing file and no failed
# lookup — only a number that was too small. So the assertion is not "does it
# return a number": it is that the number equals the variables actually in the
# file, on a fixture that contains the names the old regex skipped.
#
# The last case is the one that keeps the fix: it fails if any script goes back
# to counting with its own character class, which is how the two call sites
# drifted apart in the first place.

set -uo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${DIR}/../.." && pwd)"
# shellcheck source=./env-file.sh
source "${DIR}/env-file.sh"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

failures=0
ok() { printf '  ok    %s\n' "$1"; }
bad() { printf '  FAIL  %s\n        %s\n' "$1" "$2"; failures=$((failures + 1)); }

# name, expected count, env file body
count_is() {
  local name="$1" want="$2" body="$3"
  local file="${WORK}/env" got

  printf '%s' "$body" >"$file"
  got="$(env_variable_count "$file")"

  if [[ "$got" != "$want" ]]; then
    bad "$name" "counted ${got}, wanted ${want}"
    return
  fi
  ok "$name"
}

# --- the fixture that reproduces INF-051 -----------------------------------
# Eight of DEV's backend variables carry a digit today (`R2_*`,
# `CLOUDFLARE_R2_BUCKETS`). Under `^[A-Z_]+=` this file counted 3 of its 7.
R2_FIXTURE='# Rendered by GoGo-Infra deploy at 2026-01-01T00:00:00Z
NODE_ENV=production
APP_ENV=dev
DATABASE_URL=postgres://USER:PASSWORD@host/db
R2_ACCESS_KEY_ID=aaa
R2_BUCKET=gogo-dev
R2_ENDPOINT=https://example.r2.cloudflarestorage.com
R2_SECRET_ACCESS_KEY=bbb
'

count_is "a digit in the variable name is still a variable" 7 "$R2_FIXTURE"

# The same claim stated the other way round, so the expected number above
# cannot be quietly adjusted to whatever the code returns: the count must equal
# the lines that look like assignments, independently derived.
printf '%s' "$R2_FIXTURE" >"${WORK}/env"
declared="$(grep -c '^[^#]*=' "${WORK}/env")"
counted="$(env_variable_count "${WORK}/env")"
if [[ "$counted" == "$declared" ]]; then
  ok "the count equals the assignment lines in the file (${declared})"
else
  bad "the count equals the assignment lines in the file" \
    "helper said ${counted}, the file holds ${declared}"
fi

# --- shapes that must not inflate the total --------------------------------
count_is "comments and the generated header do not count" 1 \
  '# Generated by scripts/secrets/pull.sh
# Environment: dev   Generated: 2026-01-01T00:00:00Z
NODE_ENV=development
'

count_is "a value containing = counts once" 2 \
  'NODE_ENV=production
IDENTITY_KEY_P8_BASE64=not-a-key==
'

count_is "an indented or lowercase line is not a rendered variable" 1 \
  'NODE_ENV=production
  R2_BUCKET=indented
r2_bucket=lowercase
# R2_ENDPOINT=commented
'

# An empty file is a real state — a render that wrote nothing — and the caller
# reports it. grep exits 1 on no match, so without the helper swallowing that
# the `set -e` in render-env.sh would abort on the success path.
count_is "a file with no variables counts zero instead of failing" 0 \
  '# nothing here
'

# --- a file that cannot be read --------------------------------------------
# grep exits 2 here. Swallowing that with the "no matches" case printed 0, and
# render-env.sh then announced a finished render of zero variables for a file
# that was never read. The failure has to reach the caller.
missing="${WORK}/does-not-exist.env"
if out="$(env_variable_count "$missing" 2>/dev/null)"; then
  bad "an unreadable file is an error, not a zero" "returned success with '${out}'"
else
  ok "an unreadable file is an error, not a zero"
fi

# Same through render-env.sh's own pattern: a failing assignment under `set -e`
# stops the script before it reports anything. Run outside an `if` on purpose —
# bash ignores errexit for anything inside a condition, subshell included, so
# testing it there would pass or fail for the wrong reason.
(set -e; n="$(env_variable_count "$missing" 2>/dev/null)"; echo "rendered ${n}") >/dev/null 2>&1
caller_status=$?
if ((caller_status != 0)); then
  ok "set -e stops at a count that failed"
else
  bad "set -e stops at a count that failed" "the caller carried on and reported"
fi

# --- the regression guard ---------------------------------------------------
# render-env.sh and pull.sh each carried their own copy of this grep, and the
# fix is only durable if a third copy cannot appear. Matches a count over a
# bare upper-case character class, which is the shape that drops digits.
strays="$(grep -rnE "grep -c[a-zA-Z]* +['\"]\^\[A-Z" "${REPO_ROOT}/scripts" \
  --include='*.sh' 2>/dev/null \
  | grep -v '/env-file\.sh:' \
  | grep -v '/env-file\.test\.sh:' || true)"

if [[ -z "$strays" ]]; then
  ok "no script counts variables with its own character class"
else
  bad "no script counts variables with its own character class" \
    "use env_variable_count instead — ${strays}"
fi

# --- the call sites actually use it -----------------------------------------
for script in "${REPO_ROOT}/scripts/deploy/render-env.sh" "${REPO_ROOT}/scripts/secrets/pull.sh"; do
  name="$(basename "$script")"
  if grep -q 'env_variable_count' "$script"; then
    ok "${name} reports its count through the shared helper"
  else
    bad "${name} reports its count through the shared helper" \
      "no call to env_variable_count found"
  fi
done

printf '\n'
if [[ "$failures" -gt 0 ]]; then
  echo "${failures} failing case(s)" >&2
  exit 1
fi
echo "env-file helpers: all cases pass"
