#!/usr/bin/env bash
#
# Stage 0b — create the GitHub OIDC provider, the IAM roles and the SSM policies,
# then move this configuration's state into R2.
#
#   ./scripts/bootstrap/aws.sh [env]        # default: dev
#
# Terraform owns these resources from creation. Creating them imperatively first
# and importing later is supported (import-existing.sh) but is the worse path:
# the first managed apply otherwise fails with EntityAlreadyExists, usually in
# front of whoever is least expecting it.

set -euo pipefail

ENVIRONMENT="${1:-dev}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TF_DIR="${REPO_ROOT}/terraform/environments/${ENVIRONMENT}"
OVERRIDE="${TF_DIR}/backend_override.tf"

source "${REPO_ROOT}/scripts/lib/config.sh"
source "${REPO_ROOT}/scripts/lib/cloudflare.sh"

# The environment configurations manage Cloudflare resources, so this stage
# needs the provider token even though the visible work is IAM. Check it here:
# discovering it is missing after the IAM apply has run reads like an IAM
# failure and sends the operator looking in the wrong place.
require_cloudflare_token "/gogo/ci/${ENVIRONMENT}/terraform/write/cloudflare-token"

command -v terraform >/dev/null || { echo "terraform required" >&2; exit 1; }
aws sts get-caller-identity >/dev/null || { echo "not authenticated to AWS" >&2; exit 1; }

account_id="$(require_tfvar_string cloudflare_account_id \
  "${REPO_ROOT}/config/global.tfvars" "$CLOUDFLARE_ID_PATTERN")"

verify_cloudflare_token "$account_id"
verify_cloudflare_r2_access "$account_id"

# Checked here rather than at the migration step at the end. The apply itself
# does not need these, but the migration does — and failing after the apply
# leaves the environment created with its state still on one laptop.
source "${REPO_ROOT}/scripts/lib/r2-profile.sh"
require_ci_credentials "$ENVIRONMENT"

# Extends the existing handler rather than registering a second trap: a second
# `trap ... EXIT` replaces the first, and the override file would then be left
# behind — after which every later `terraform init` in that directory silently
# uses a local backend.
cleanup() { rm -f "$OVERRIDE"; }
trap cleanup EXIT

# Refuse to run against an environment whose state is already remote.
#
# This script starts from an empty local state by design — that is what makes a
# first bootstrap possible. Run a second time on a migrated environment, it does
# not read the remote state at all: it plans as if nothing exists and tries to
# create everything again. That produced a 409 on an R2 bucket that already
# existed, and left a real IAM policy recorded only in a throwaway local state
# file, invisible to the environment that owns it.
#
# For an environment that is already bootstrapped, use terraform directly or the
# CI workflow.
if [[ "$(jq -r '.backend.type // "none"' "${TF_DIR}/.terraform/terraform.tfstate" 2>/dev/null)" == "s3" ]] \
   && [[ "${GOGO_REBOOTSTRAP:-}" != "1" ]]; then
  cat >&2 <<MSG
error: ${ENVIRONMENT} already uses the remote backend.

  This script bootstraps from empty local state. Running it now would plan as if
  nothing exists and try to create resources that are already there.

  To apply a change to an existing environment:

    source scripts/lib/r2-profile.sh
    write_r2_profile /gogo/ci/${ENVIRONMENT}/terraform/write
    export CLOUDFLARE_API_TOKEN="\$(aws ssm get-parameter \\
      --name /gogo/ci/${ENVIRONMENT}/terraform/write/cloudflare-token \\
      --with-decryption --query 'Parameter.Value' --output text)"
    terraform -chdir=${TF_DIR} apply \\
      -var-file=../../../config/global.tfvars \\
      -var-file=../../../config/${ENVIRONMENT}.tfvars

  Or run the terraform-apply-${ENVIRONMENT} workflow.
MSG
  exit 1
fi

# The remote backend cannot be used yet: reaching it needs the R2 credentials
# that the roles created here will eventually grant access to. Start local,
# then migrate.
echo "==> Applying with local state"
cat >"$OVERRIDE" <<'HCL'
# Generated by scripts/bootstrap/aws.sh. Removed automatically.
terraform {
  backend "local" {}
}
HCL

terraform -chdir="$TF_DIR" init -input=false -reconfigure
terraform -chdir="$TF_DIR" apply -input=false -auto-approve \
  -var-file=../../../config/global.tfvars \
  -var-file="../../../config/${ENVIRONMENT}.tfvars"

echo "==> Migrating state into R2"
cleanup
trap - EXIT

write_r2_profile "/gogo/ci/${ENVIRONMENT}/terraform/write"

# -force-copy answers the migration prompt. Without it, -migrate-state asks for
# approval and -input=false refuses to ask, so init fails having done nothing.
terraform -chdir="$TF_DIR" init -input=false -force-copy -migrate-state \
  -backend-config="endpoints={s3=\"https://${account_id}.r2.cloudflarestorage.com\"}"

echo "==> Verifying"
terraform -chdir="$TF_DIR" plan -input=false -detailed-exitcode \
  -var-file=../../../config/global.tfvars \
  -var-file="../../../config/${ENVIRONMENT}.tfvars" && echo "plan is clean" || {
    code=$?
    [[ "$code" == "2" ]] && echo "warning: plan reports pending changes; review before continuing" >&2
  }

echo
echo "Delete any leftover local state once the plan above is clean:"
echo "  rm -f ${TF_DIR}/terraform.tfstate*"
echo
echo "Next: ./scripts/bootstrap/complete.sh ${ENVIRONMENT}"
