#!/usr/bin/env bash
#
# Stage 0b — create the GitHub OIDC provider, the IAM roles and the SSM policies,
# then move this configuration's state into R2.
#
#   ./scripts/bootstrap/aws.sh [env]        # default: dev
#
# Terraform owns these resources from creation. Creating them imperatively first
# and importing later is supported (import-existing.sh) but is the worse path:
# the first managed apply otherwise fails with EntityAlreadyExists, usually in
# front of whoever is least expecting it.

set -euo pipefail

ENVIRONMENT="${1:-dev}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TF_DIR="${REPO_ROOT}/terraform/environments/${ENVIRONMENT}"
OVERRIDE="${TF_DIR}/backend_override.tf"

source "${REPO_ROOT}/scripts/lib/config.sh"
source "${REPO_ROOT}/scripts/lib/cloudflare.sh"

# The environment configurations manage Cloudflare resources, so this stage
# needs the provider token even though the visible work is IAM. Check it here:
# discovering it is missing after the IAM apply has run reads like an IAM
# failure and sends the operator looking in the wrong place.
require_cloudflare_token

command -v terraform >/dev/null || { echo "terraform required" >&2; exit 1; }
aws sts get-caller-identity >/dev/null || { echo "not authenticated to AWS" >&2; exit 1; }

account_id="$(require_tfvar_string cloudflare_account_id \
  "${REPO_ROOT}/config/global.tfvars" "$CLOUDFLARE_ID_PATTERN")"

verify_cloudflare_token "$account_id"
verify_cloudflare_r2_access "$account_id"

# Extends the existing handler rather than registering a second trap: a second
# `trap ... EXIT` replaces the first, and the override file would then be left
# behind — after which every later `terraform init` in that directory silently
# uses a local backend.
cleanup() { rm -f "$OVERRIDE"; }
trap cleanup EXIT

# The remote backend cannot be used yet: reaching it needs the R2 credentials
# that the roles created here will eventually grant access to. Start local,
# then migrate.
echo "==> Applying with local state"
cat >"$OVERRIDE" <<'HCL'
# Generated by scripts/bootstrap/aws.sh. Removed automatically.
terraform {
  backend "local" {}
}
HCL

terraform -chdir="$TF_DIR" init -input=false -reconfigure
terraform -chdir="$TF_DIR" apply -input=false -auto-approve \
  -var-file=../../../config/global.tfvars \
  -var-file="../../../config/${ENVIRONMENT}.tfvars"

echo "==> Migrating state into R2"
cleanup
trap - EXIT

source "${REPO_ROOT}/scripts/lib/r2-profile.sh"
write_r2_profile "/gogo/ci/${ENVIRONMENT}/terraform/write"

terraform -chdir="$TF_DIR" init -input=false -migrate-state \
  -backend-config="endpoints={s3=\"https://${account_id}.r2.cloudflarestorage.com\"}"

echo "==> Verifying"
terraform -chdir="$TF_DIR" plan -input=false -detailed-exitcode \
  -var-file=../../../config/global.tfvars \
  -var-file="../../../config/${ENVIRONMENT}.tfvars" && echo "plan is clean" || {
    code=$?
    [[ "$code" == "2" ]] && echo "warning: plan reports pending changes; review before continuing" >&2
  }

echo
echo "Delete any leftover local state once the plan above is clean:"
echo "  rm -f ${TF_DIR}/terraform.tfstate*"
echo
echo "Next: ./scripts/bootstrap/complete.sh ${ENVIRONMENT}"
