#!/usr/bin/env bash
#
# Materialise the environment's parameters into a local .env.runtime file.
#
#   ./scripts/secrets/pull.sh dev
#   ./scripts/secrets/pull.sh dev --out ../GoGo-BE/.env.runtime
#
# Fetches once per session rather than calling SSM per request. The output file
# is written with mode 0600 and is gitignored.

source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

ENVIRONMENT="${1:-}"
require_env_arg "$ENVIRONMENT"
shift || true

OUT_FILE=".env.runtime"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --out)
      OUT_FILE="${2:-}"
      shift 2
      ;;
    *) die "unknown argument: $1" ;;
  esac
done

if [[ "$ENVIRONMENT" == "prod" && "${GOGO_ALLOW_PROD_PULL:-}" != "1" ]]; then
  die "refusing to pull production secrets onto a developer machine.
       Production secrets are injected during deploy by .github/workflows/deploy-production.yml.
       Override only for an incident, with GOGO_ALLOW_PROD_PULL=1, and note it in docs/secrets.md."
fi

require_aws

prefix="$(ssm_prefix "$ENVIRONMENT")"
tmp_file="$(mktemp)"
trap 'rm -f "$tmp_file"' EXIT
chmod 600 "$tmp_file"

{
  echo "# Generated by scripts/secrets/pull.sh from ${prefix}/*"
  echo "# Environment: ${ENVIRONMENT}   Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "# Do not commit. Do not paste into a ticket. Re-run the script instead of sharing it."
  echo "NODE_ENV=development"
  echo "APP_ENV=${ENVIRONMENT}"
} >"$tmp_file"

missing=0
while IFS=$'\t' read -r path env_var _type required _namespace; do
  [[ -n "$env_var" ]] || continue

  if ! value="$(aws ssm get-parameter --name "${prefix}/${path}" --with-decryption --query 'Parameter.Value' --output text 2>/dev/null)"; then
    if [[ ",${required}," == *",${ENVIRONMENT},"* ]]; then
      echo "missing required parameter: ${prefix}/${path}" >&2
      missing=$((missing + 1))
    fi
    continue
  fi

  printf '%s=%s\n' "$env_var" "$value" >>"$tmp_file"
  unset value
# `backend` is stated rather than inherited. This file becomes GoGo-BE's
# environment; a mobile build key belongs in a mobile build, not in the API's
# process env, and it lives under a prefix this prefix cannot even reach.
done < <(python3 "$MANIFEST_READER" "$ENVIRONMENT" --namespace backend)

if [[ "$missing" -gt 0 ]]; then
  die "${missing} required parameter(s) missing. Run ./scripts/secrets/validate.sh ${ENVIRONMENT} for the full diff."
fi

install -m 600 "$tmp_file" "$OUT_FILE"
variable_count=$(grep -cE '^[A-Z_]+=' "$OUT_FILE")
echo "wrote ${OUT_FILE} (mode 0600, ${variable_count} variables)"
