#!/usr/bin/env bash
#
# Materialise the environment's parameters into a local .env.runtime file.
#
#   ./scripts/secrets/pull.sh dev
#   ./scripts/secrets/pull.sh dev --out ../GoGo-BE/.env.runtime
#   ./scripts/secrets/pull.sh dev --seed          # -> .env.seed, adds the seed-only rows
#
# Fetches once per session rather than calling SSM per request. The output file
# is written with mode 0600 and is gitignored.
#
# --seed adds the parameters declared `consumer: seed` (INF-069) on top of the
# runtime ones, because a provisioning command needs both DATABASE_URL and its
# own inputs. It writes a *different file by default* rather than widening
# .env.runtime, and that is the entire point: .env.runtime is the file a
# developer keeps loaded all day and the shape the deployed env file copies.
# Shred the seed file when the command that needed it has finished.

source "$(dirname "${BASH_SOURCE[0]}")/common.sh"
# shellcheck source=../lib/place-refresh-budget.sh
source "${REPO_ROOT}/scripts/lib/place-refresh-budget.sh"
# shellcheck source=../lib/env-file.sh
source "${REPO_ROOT}/scripts/lib/env-file.sh"

ENVIRONMENT="${1:-}"
require_env_arg "$ENVIRONMENT"
shift || true

OUT_FILE=""
CONSUMER="runtime"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --out)
      OUT_FILE="${2:-}"
      shift 2
      ;;
    --seed)
      CONSUMER="all"
      shift
      ;;
    *) die "unknown argument: $1" ;;
  esac
done

# Defaulted after parsing so --out wins regardless of flag order, and so the
# two modes cannot land on the same filename by accident.
if [[ -z "$OUT_FILE" ]]; then
  [[ "$CONSUMER" == "all" ]] && OUT_FILE=".env.seed" || OUT_FILE=".env.runtime"
fi

if [[ "$ENVIRONMENT" == "prod" && "${GOGO_ALLOW_PROD_PULL:-}" != "1" ]]; then
  die "refusing to pull production secrets onto a developer machine.
       Production secrets are injected during deploy by .github/workflows/deploy-production.yml.
       Override only for an incident, with GOGO_ALLOW_PROD_PULL=1, and note it in docs/secrets.md."
fi

require_aws

prefix="$(ssm_prefix "$ENVIRONMENT")"
tmp_file="$(mktemp)"
trap 'rm -f "$tmp_file"' EXIT
chmod 600 "$tmp_file"

{
  echo "# Generated by scripts/secrets/pull.sh from ${prefix}/*"
  echo "# Environment: ${ENVIRONMENT}   Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "# Do not commit. Do not paste into a ticket. Re-run the script instead of sharing it."
  echo "NODE_ENV=development"
  echo "APP_ENV=${ENVIRONMENT}"
} >"$tmp_file"

missing=0
while IFS=$'\t' read -r path env_var _type required _namespace; do
  [[ -n "$env_var" ]] || continue

  if ! value="$(aws ssm get-parameter --name "${prefix}/${path}" --with-decryption --query 'Parameter.Value' --output text 2>/dev/null)"; then
    if [[ ",${required}," == *",${ENVIRONMENT},"* ]]; then
      echo "missing required parameter: ${prefix}/${path}" >&2
      missing=$((missing + 1))
    fi
    continue
  fi

  printf '%s=%s\n' "$env_var" "$value" >>"$tmp_file"
  unset value
# `backend` is stated rather than inherited. This file becomes GoGo-BE's
# environment; a mobile build key belongs in a mobile build, not in the API's
# process env, and it lives under a prefix this prefix cannot even reach.
#
# The consumer is stated for the same reason and defaults to `runtime`: without
# --seed this file must not carry the CMS bootstrap password, because the API
# started from it would then hold a super_admin credential it never uses.
done < <(python3 "$MANIFEST_READER" "$ENVIRONMENT" --namespace backend --consumer "$CONSUMER")

if [[ "$missing" -gt 0 ]]; then
  die "${missing} required parameter(s) missing. Run ./scripts/secrets/validate.sh ${ENVIRONMENT} for the full diff."
fi

install -m 600 "$tmp_file" "$OUT_FILE"
variable_count=$(env_variable_count "$OUT_FILE")
echo "wrote ${OUT_FILE} (mode 0600, ${variable_count} variables)"

if [[ "$CONSUMER" == "all" ]]; then
  echo "  Includes seed-only parameters. Shred it when the provisioning command is done:"
  echo "    shred -u ${OUT_FILE} 2>/dev/null || rm -P ${OUT_FILE}"
fi

# INF-057. Same default-deny budget as a deploy, same silence: a local API with
# four of the five ceilings set refreshes nothing and says nothing about it.
#
# Unlike render-env.sh this keeps the file it just wrote. A deploy shreds a
# broken env file because nothing should run on it; a developer is usually here
# *because* the environment is wrong, and taking the evidence away is not help.
if ! place_refresh_budget_report "$OUT_FILE"; then
  echo "${OUT_FILE} was written and kept — fix the ceilings in SSM, then pull again." >&2
  exit 1
fi
