#!/usr/bin/env bash
#
# Tests for put-identity-key.sh.
#
#   ./scripts/secrets/put-identity-key.test.sh
#
# Every key here is generated by this file and thrown away with the sandbox. A
# real OneSignal key is never needed to test this, and must never be used to.
#
# What is worth asserting is not the happy path against AWS — that needs an
# account — but that a wrong key is refused *before* the upload, that an
# existing parameter is not replaced by accident, and that the key never
# reaches a command line, an environment variable, a file, or the output.

set -uo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT="${DIR}/put-identity-key.sh"
FAILED=0

pass() { printf '  ok    %s\n' "$1"; }
fail() {
  printf '  FAIL  %s\n' "$1"
  FAILED=1
}

SANDBOX="$(mktemp -d)"
trap 'rm -rf "$SANDBOX"' EXIT
umask 077

# --- fixtures ----------------------------------------------------------------
#
# One correct key in each of the two encodings OneSignal could hand out, and
# one of every wrong thing that has plausibly been pasted into this slot.
KEYS="${SANDBOX}/keys"
mkdir -p "$KEYS"
openssl ecparam -name prime256v1 -genkey -noout -out "${KEYS}/p256-sec1.pem" 2>/dev/null
openssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:P-256 -out "${KEYS}/p256-pkcs8.pem" 2>/dev/null
openssl ecparam -name secp384r1 -genkey -noout -out "${KEYS}/p384.pem" 2>/dev/null
openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out "${KEYS}/rsa.pem" 2>/dev/null
openssl pkey -in "${KEYS}/p256-sec1.pem" -pubout -out "${KEYS}/public.pem" 2>/dev/null
openssl pkey -in "${KEYS}/p256-sec1.pem" -aes256 -passout pass:hunter2 -out "${KEYS}/encrypted.pem" 2>/dev/null
printf 'os_v2_app_not_a_key\n' >"${KEYS}/rest-api-key.pem"
chmod 600 "${KEYS}"/*.pem

# The plaintext of the good key, so the assertions can prove it never appears
# anywhere. Held in this test only.
SECRET_LINE="$(sed -n '2p' "${KEYS}/p256-sec1.pem")"

# --- stubs -------------------------------------------------------------------
#
# Exported, or the stubs inherit an empty CALLS, write nowhere, and every
# assertion passes against a file that never filled — while a real `aws` runs
# against a real account. That happened once already, on put-worker-secret.sh,
# and put a secret on the DEV worker.
export CALLS="${SANDBOX}/calls"
export STORED="${SANDBOX}/stored"
export STUB_ACCOUNT_FILE="${SANDBOX}/account"
export STUB_EXISTING_FILE="${SANDBOX}/existing"
: >"$CALLS"

# From config/global.tfvars — the script reads the expected account from there,
# so the stub must agree with the file rather than with a second copy here.
REAL_ACCOUNT="$(sed -nE 's/^[[:space:]]*aws_account_id[[:space:]]*=[[:space:]]*"([^"]*)".*/\1/p' "${DIR}/../../config/global.tfvars")"

cat >"${SANDBOX}/aws" <<'STUB'
#!/usr/bin/env bash
[[ -n "${CALLS:-}" ]] || { echo "stub: CALLS is unset, refusing to continue" >&2; exit 97; }
# Arguments are recorded, and the recording is what later assertions grep for a
# leaked key. So this must log argv verbatim, never a sanitised version.
echo "aws $*" >> "$CALLS"
case "$*" in
  *"sts get-caller-identity"*"--query"*)
    cat "$STUB_ACCOUNT_FILE" ;;
  *"sts get-caller-identity"*)
    echo '{"Account":"stub"}' ;;
  *get-parameter*--with-decryption*)
    cat "$STORED" ;;
  *get-parameter*)
    # Absent unless a test says otherwise: `get-parameter` failing is how the
    # script learns the parameter does not exist yet.
    [[ -s "$STUB_EXISTING_FILE" ]] || exit 255
    cat "$STUB_EXISTING_FILE" ;;
  *put-parameter*)
    # Pull the value out of the request file the way the CLI would, and keep it
    # where the read-back can find it. Its length is recorded; its content is
    # not, because a test that logs the secret is the leak it is testing for.
    # Scanned rather than pattern-stripped off "$*": ${*##pat} applies the
    # removal to each positional parameter in turn, which returns "ssm".
    file=""
    for arg in "$@"; do
      case "$arg" in file://*) file="${arg#file://}" ;; esac
    done
    python3 -c 'import json,os,sys
d=json.load(open(sys.argv[1]))
open(os.environ["STORED"],"w").write(d["Value"])
print("put-parameter Name=%s Type=%s Overwrite=%s value-bytes=%d"
      % (d["Name"], d["Type"], d["Overwrite"], len(d["Value"])),
      file=open(os.environ["CALLS"],"a"))' "$file"
    echo 7 ;;
esac
STUB
chmod +x "${SANDBOX}/aws"

echo "$REAL_ACCOUNT" >"$STUB_ACCOUNT_FILE"
: >"$STUB_EXISTING_FILE"
: >"$STORED"

run() {
  : >"$CALLS"
  : >"$STORED"
  # PATH replaced, not prefixed: a stub that failed to be created must break
  # the test, not fall through to the real aws.
  PATH="${SANDBOX}:/usr/bin:/bin" AWS_PROFILE=stub "$SCRIPT" "$@" 2>&1
}

echo "put-identity-key.sh"

# --- arguments ---------------------------------------------------------------

out="$(run "${KEYS}/p256-sec1.pem")"
if [[ "$out" == *usage* ]]; then pass "missing environment prints usage"; else fail "missing environment prints usage"; fi

out="$(run "${KEYS}/p256-sec1.pem" not-an-env)"
if [[ "$out" == *"environment must be one of"* ]] && ! grep -q put-parameter "$CALLS"; then
  pass "an unknown environment is refused before AWS"
else
  fail "an unknown environment is refused before AWS"
fi

out="$(run "${KEYS}/nope.pem" dev)"
if [[ "$out" == *"no such file"* ]] && ! grep -q put-parameter "$CALLS"; then
  pass "a missing file is refused before AWS"
else
  fail "a missing file is refused before AWS"
fi

out="$(run "${KEYS}/p256-sec1.pem" dev --profile)"
if [[ "$out" == *"--profile needs a value"* ]]; then
  pass "--profile without a value is refused"
else
  fail "--profile without a value is refused"
fi

# --- the file's own hygiene --------------------------------------------------

cp "${KEYS}/p256-sec1.pem" "${SANDBOX}/loose.pem"
chmod 644 "${SANDBOX}/loose.pem"
out="$(run "${SANDBOX}/loose.pem" dev)"
if [[ "$out" == *"must be 0600"* ]] && ! grep -q put-parameter "$CALLS"; then
  pass "a world-readable key file is refused"
else
  fail "a world-readable key file is refused"
fi

# A key inside a working tree is one `git add -A` from a public repository.
# `.gitignore` covers *.pem; a rename or `git add -f` does not care.
GITREPO="${SANDBOX}/repo"
mkdir -p "$GITREPO"
git -C "$GITREPO" init -q 2>/dev/null
cp "${KEYS}/p256-sec1.pem" "${GITREPO}/onesignal-identity.pem"
chmod 600 "${GITREPO}/onesignal-identity.pem"
out="$(run "${GITREPO}/onesignal-identity.pem" dev)"
if [[ "$out" == *"inside a git working tree"* ]] && ! grep -q put-parameter "$CALLS"; then
  pass "a key inside a git working tree is refused"
else
  fail "a key inside a git working tree is refused"
fi

# --- the key itself ----------------------------------------------------------

for bad in p384 rsa; do
  out="$(run "${KEYS}/${bad}.pem" dev)"
  if [[ "$out" == *"not on curve P-256"* ]] && ! grep -q put-parameter "$CALLS"; then
    pass "a ${bad} key is refused: wrong curve for ES256"
  else
    fail "a ${bad} key is refused: wrong curve for ES256"
  fi
done

for bad in public encrypted rest-api-key; do
  out="$(run "${KEYS}/${bad}.pem" dev)"
  if [[ "$out" == *"not an unencrypted private key"* ]] && ! grep -q put-parameter "$CALLS"; then
    pass "${bad}.pem is refused before the upload"
  else
    fail "${bad}.pem is refused before the upload"
  fi
done

# --- wrong AWS account -------------------------------------------------------

echo "000000000000" >"$STUB_ACCOUNT_FILE"
out="$(run "${KEYS}/p256-sec1.pem" dev)"
if [[ "$out" == *"wrong AWS account"* ]] && [[ "$out" == *"$REAL_ACCOUNT"* ]] && ! grep -q put-parameter "$CALLS"; then
  pass "a session in another AWS account is refused before the upload"
else
  fail "a session in another AWS account is refused before the upload"
fi
echo "$REAL_ACCOUNT" >"$STUB_ACCOUNT_FILE"

# --- overwrite is opt-in -----------------------------------------------------

echo "4" >"$STUB_EXISTING_FILE"
out="$(run "${KEYS}/p256-sec1.pem" dev)"
if [[ "$out" == *"already exists (version 4)"* ]] && ! grep -q put-parameter "$CALLS"; then
  pass "an existing parameter is not replaced without --overwrite"
else
  fail "an existing parameter is not replaced without --overwrite"
fi

out="$(run "${KEYS}/p256-sec1.pem" dev --overwrite)"
if [[ "$out" == *"overwriting"* ]] && grep -q put-parameter "$CALLS"; then
  pass "--overwrite replaces an existing parameter"
else
  fail "--overwrite replaces an existing parameter"
fi
: >"$STUB_EXISTING_FILE"

# --- the upload --------------------------------------------------------------

out="$(run "${KEYS}/p256-sec1.pem" dev)"

if [[ "$out" == *"verified:"* && "$out" == *"version:  7"* ]]; then
  pass "a P-256 SEC1 key uploads and verifies"
else
  fail "a P-256 SEC1 key uploads and verifies"
fi

if [[ "$out" == *"/gogo/dev/backend/onesignal/identity-verification-key"* ]]; then
  pass "it writes the manifest's path in the backend namespace"
else
  fail "it writes the manifest's path in the backend namespace"
fi

if grep -q "put-parameter Name=/gogo/dev/backend/onesignal/identity-verification-key Type=SecureString" "$CALLS"; then
  pass "the parameter is a SecureString"
else
  fail "the parameter is a SecureString"
fi

out2="$(run "${KEYS}/p256-pkcs8.pem" dev)"
if [[ "$out2" == *"verified:"* ]]; then
  pass "a P-256 PKCS#8 key uploads and verifies"
else
  fail "a P-256 PKCS#8 key uploads and verifies"
fi

# --- the encoding the renderers can actually carry ---------------------------
#
# render-env.sh:42 and pull.sh:82 are both `printf '%s=%s\n'`. Anything with a
# newline in it produces orphan lines no env parser can attach to a variable.
run "${KEYS}/p256-sec1.pem" dev >/dev/null
# -s first. An empty $STORED — which is what a die *before* the upload leaves
# behind — has zero lines and matches no forbidden pattern, so without this the
# next three assertions pass by never having run. That is exactly how a
# BSD-only `stat` call reached CI green locally and failed on Linux.
if [[ -s "$STORED" && "$(wc -l <"$STORED" | tr -d ' ')" == "0" ]]; then
  pass "the stored value is a single line"
else
  fail "the stored value is a single line"
fi

if grep -qE '^[A-Za-z0-9+/]+=*$' "$STORED"; then
  pass "the stored value is base64 — no character special to a shell, JSON or env parser"
else
  fail "the stored value is base64 — no character special to a shell, JSON or env parser"
fi

# The contract with GoGo-BE's parseIdentitySigningKey: base64 of the whole PEM.
decoded="$(openssl base64 -d -A -in "$STORED" 2>/dev/null | head -1)"
if [[ "$decoded" == "-----BEGIN"* ]]; then
  pass "it decodes to the PEM GoGo-BE expects"
else
  fail "it decodes to the PEM GoGo-BE expects"
fi

# --- the key never leaks -----------------------------------------------------

if [[ "$out" != *"$SECRET_LINE"* ]]; then
  pass "no key material is printed"
else
  fail "no key material is printed"
fi

if ! grep -qF -- "$SECRET_LINE" "$CALLS"; then
  pass "no key material reaches a command line"
else
  fail "no key material reaches a command line"
fi

# put-parameter carries the value in a --cli-input-json file, never in argv.
if grep -q -- "--cli-input-json file://" "$CALLS" && ! grep -q -- "--value" "$CALLS"; then
  pass "the value goes to the CLI in a file, not as --value"
else
  fail "the value goes to the CLI in a file, not as --value"
fi

# The request file is created under mktemp and removed; nothing survives.
if [[ -z "$(find "${TMPDIR:-/tmp}" -maxdepth 1 -name 'tmp.*' -newer "${KEYS}/p256-sec1.pem" -exec grep -lF -- "$SECRET_LINE" {} + 2>/dev/null)" ]]; then
  pass "no temporary file is left holding the key"
else
  fail "no temporary file is left holding the key"
fi

# --- tracing -----------------------------------------------------------------
#
# `set -x` would print every expansion, the base64 of the key included, into
# whatever is capturing the shell.
out="$(PATH="${SANDBOX}:/usr/bin:/bin" AWS_PROFILE=stub bash -x "$SCRIPT" "${KEYS}/p256-sec1.pem" dev 2>&1)"
if [[ "$out" == *"refusing to run with shell tracing"* ]]; then
  pass "it refuses to run under shell tracing"
else
  fail "it refuses to run under shell tracing"
fi

# --- the repository holds no key ---------------------------------------------

REPO="$(cd "${DIR}/../.." && pwd)"
if ! git -C "$REPO" ls-files | grep -qE '\.(pem|key|p8)$'; then
  pass "no key file is tracked in the repository"
else
  fail "no key file is tracked in the repository"
fi

if [[ "$FAILED" -eq 0 ]]; then
  echo "all put-identity-key.sh tests passed"
else
  echo "put-identity-key.sh tests FAILED" >&2
fi
exit "$FAILED"
