#!/usr/bin/env python3
"""Merge only environment-scoped public Tenjin SDK config into a mobile env file."""

import argparse
import importlib.util
from pathlib import Path
import re

spec = importlib.util.spec_from_file_location("mobile_env", Path(__file__).with_name("mobile-env.py"))
mobile = importlib.util.module_from_spec(spec)
spec.loader.exec_module(mobile)

KEYS = ("TENJIN_IOS_SDK_KEY", "TENJIN_ANDROID_SDK_KEY")


def read_values(path):
    values = {}
    for line in Path(path).read_text().splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        match = re.fullmatch(r"([A-Z][A-Z0-9_]*)=(.*)", line.strip())
        if not match:
            raise ValueError("Invalid config assignment")
        value = match[2].strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in ('"', "'"):
            value = value[1:-1]
        values[match[1]] = value
    return values


def scoped_values(config, environment):
    result = {"TENJIN_CONFIG_ENV": environment}
    for key in KEYS:
        suffixed = f"{key}_{environment.upper()}"
        if suffixed in config:
            value = config[suffixed]
        elif config.get("UNSUFFIXED_VALUES_BELONG_TO") == environment:
            value = config.get(key, "")
        else:
            value = ""
        if not value or not re.fullmatch(r"[A-Za-z0-9_-]+", value):
            raise ValueError(f"Missing/invalid {suffixed}; no cross-environment fallback")
        result[key] = value
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("environment", choices=mobile.FLAVORS)
    parser.add_argument("--bootstrap", required=True)
    parser.add_argument("--out", required=True, help="Existing file generated by mobile-env.py")
    args = parser.parse_args()
    try:
        existing = read_values(args.out)
        if existing.get("EXPO_PUBLIC_ENV") != mobile.FLAVORS[args.environment] or existing.get("ONESIGNAL_CONFIG_ENV") != args.environment:
            raise ValueError("Destination belongs to a different environment")
        if any("SECRET" in key or "REST_API_KEY" in key or "PRIVATE_KEY" in key for key in existing):
            raise ValueError("Destination contains server-only keys")
        existing.update(scoped_values(read_values(args.bootstrap), args.environment))
        mobile.write_env(args.out, existing)
    except (ValueError, OSError) as error:
        # Validation errors contain names/reasons only, never configuration values.
        parser.exit(1, f"Tenjin configuration refused: {error}\n")
    print(f"Updated {args.out}: {args.environment} Tenjin client keys, mode 0600; no values printed")


if __name__ == "__main__":
    main()
